// sync-tokens.mjs — converts tokens.json into tokens.css
// Run after editing tokens in Figma and re-exporting tokens.json:
//   npm run sync-tokens
//
// Workflow:
//   1. Edit tokens visually in Figma (via Tokens Studio plugin)
//   2. Export from Tokens Studio → overwrites src/styles/tokens.json
//   3. Run `npm run sync-tokens`
//   4. tokens.css is regenerated → app refreshes automatically

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const projectRoot = path.resolve(__dirname, '..');

const TOKENS_JSON = path.join(projectRoot, 'src', 'styles', 'tokens.json');
const TOKENS_CSS  = path.join(projectRoot, 'src', 'styles', 'tokens.css');

// Maps tokens.json key paths to CSS variable names (kebab-case)
// e.g. color.bg.primary → --color-bg-primary
function toCssVarName(keyPath) {
  return '--' + keyPath
    .map(k => k.replace(/([A-Z])/g, '-$1').toLowerCase())
    .join('-');
}

// Walks the tokens tree, yielding [keyPath, valueObject] for every leaf token
function* walkTokens(obj, path = []) {
  for (const [key, value] of Object.entries(obj)) {
    if (key.startsWith('$')) continue; // skip metadata keys
    const newPath = [...path, key];
    if (value && typeof value === 'object' && 'value' in value && 'type' in value) {
      yield [newPath, value];
    } else if (value && typeof value === 'object') {
      yield* walkTokens(value, newPath);
    }
  }
}

function generateCss(tokens) {
  const lines = [
    '/* ============================================================',
    '   CodePath Design Tokens — auto-derived from tokens.json',
    '   ============================================================',
    '   ⚠️ DO NOT edit this file directly!',
    '   Edit tokens.json (or use Figma Tokens Studio plugin) instead,',
    '   then run: npm run sync-tokens',
    '   ============================================================ */',
    '',
    '/* Generated: ' + new Date().toISOString() + ' */',
    '',
    ':root {',
  ];

  // Group tokens by top-level key (color, font, spacing, etc.) for readability
  const grouped = new Map();
  for (const [keyPath, tok] of walkTokens(tokens)) {
    const group = keyPath[0];
    if (!grouped.has(group)) grouped.set(group, []);
    grouped.get(group).push([keyPath, tok]);
  }

  for (const [group, entries] of grouped) {
    lines.push(`  /* ===== ${group.toUpperCase()} ===== */`);
    for (const [keyPath, tok] of entries) {
      const varName = toCssVarName(keyPath);
      const comment = tok.description ? ` /* ${tok.description} */` : '';
      lines.push(`  ${varName}: ${tok.value};${comment}`);
    }
    lines.push('');
  }

  // Preserve legacy aliases that existing code uses
  lines.push('  /* ===== LEGACY ALIASES ===== */');
  const aliases = {
    '--bg-primary':     'var(--color-bg-primary)',
    '--bg-secondary':   'var(--color-bg-secondary)',
    '--bg-tertiary':    'var(--color-bg-tertiary)',
    '--bg-card':        'var(--color-bg-card)',
    '--text':           'var(--color-text-primary)',
    '--text-secondary': 'var(--color-text-secondary)',
    '--text-muted':     'var(--color-text-muted)',
    '--accent-green':   'var(--color-semantic-success)',
    '--accent-amber':   'var(--color-semantic-warning)',
    '--accent-red':     'var(--color-semantic-error)',
    '--accent-blue':    'var(--color-semantic-info)',
    '--accent-purple':  'var(--color-brand-primary)',
    '--border':         'var(--color-ui-border)',
    '--success':        'var(--color-semantic-success)',
    '--error':          'var(--color-semantic-error)',
    '--warning':        'var(--color-semantic-warning)',
    '--card':           'var(--color-bg-card)',
  };
  for (const [alias, value] of Object.entries(aliases)) {
    lines.push(`  ${alias}: ${value};`);
  }

  lines.push('}', '');
  return lines.join('\n');
}

function main() {
  if (!fs.existsSync(TOKENS_JSON)) {
    console.error(`✗ tokens.json not found at ${TOKENS_JSON}`);
    process.exit(1);
  }

  const tokens = JSON.parse(fs.readFileSync(TOKENS_JSON, 'utf8'));
  const css = generateCss(tokens);
  fs.writeFileSync(TOKENS_CSS, css);

  const tokenCount = [...walkTokens(tokens)].length;
  console.log(`✓ Generated ${TOKENS_CSS}`);
  console.log(`✓ ${tokenCount} tokens synced from tokens.json`);
  console.log(`\nNext: refresh the app — Vite picks up the change automatically.`);
}

main();
